-- AlterTable
ALTER TABLE `invitation` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `subAccountId` VARCHAR(191) NULL,
    ADD COLUMN `updatedAt` DATETIME(3) NULL;
